# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_example', [dirname(__file__)])
        except ImportError:
            import _example
            return _example
        if fp is not None:
            try:
                _mod = imp.load_module('_example', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _example = swig_import_helper()
    del swig_import_helper
else:
    import _example
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def fact(*args):
  return _example.fact(*args)
fact = _example.fact

def my_mod(*args):
  return _example.my_mod(*args)
my_mod = _example.my_mod

def my_array(*args):
  return _example.my_array(*args)
my_array = _example.my_array

def my_ptr(*args):
  return _example.my_ptr(*args)
my_ptr = _example.my_ptr
class Test(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Test, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Test, name)
    __repr__ = _swig_repr
    __swig_setmethods__["a"] = _example.Test_a_set
    __swig_getmethods__["a"] = _example.Test_a_get
    if _newclass:a = _swig_property(_example.Test_a_get, _example.Test_a_set)
    __swig_setmethods__["b"] = _example.Test_b_set
    __swig_getmethods__["b"] = _example.Test_b_get
    if _newclass:b = _swig_property(_example.Test_b_get, _example.Test_b_set)
    def __init__(self): 
        this = _example.new_Test()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _example.delete_Test
    __del__ = lambda self : None;
Test_swigregister = _example.Test_swigregister
Test_swigregister(Test)
cvar = _example.cvar

# This file is compatible with both classic and new-style classes.


